sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  matrix:
    - CI_ROS_DISTRO="jade"
    - CI_ROS_DISTRO="indigo"
    
install:
  - rvm use 1.9.3 --install --fuzzy
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo apt-get install -qq -y ros-$CI_ROS_DISTRO-catkin ros-$CI_ROS_DISTRO-ros
  - sudo rosdep init
  - rosdep update
  - sudo apt-get install -qq -y ros-indigo-orogen
  - ruby -e 'puts $:'
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - ruby -e 'puts $:'
  - echo $RUBYLIB
  - echo $RUBYOPT
  - echo $PATH

script:
  - typegen
  - orogen
